# Generated by Django 4.2.5 on 2023-10-13 14:03

import dotenv
import os
from django.db import migrations

dotenv.load_dotenv()

def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    ADMIN_USERNAME  = os.environ.get("ADMIN_USERNAME")

    secret_file = os.environ.get("ADMIN_PASSWORD_FILE")
    if secret_file and not os.path.exists(secret_file):
        secret_file = os.path.join(os.getcwd(), secret_file)
    if secret_file:
        with open(secret_file, 'r') as fd:
            ADMIN_PASSWORD = ''.join([line.strip() for line in fd.readlines()])
    else:
        ADMIN_PASSWORD  = os.environ.get("ADMIN_PASSWORD")

    ADMIN_EMAIL     = os.environ.get("ADMIN_EMAIL")

    user = get_user_model()

    if not user.objects.filter(username=ADMIN_USERNAME, email=ADMIN_EMAIL).exists():
        # logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
                    username=ADMIN_USERNAME,
                    password=ADMIN_PASSWORD,
                    email=ADMIN_EMAIL
                )
        admin.save()
    # else:
    #     logger.info("Superuser already created!")

class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
