# Generated by Django 4.2.5 on 2023-10-11 18:05

from django.db import migrations
from ..management.commands import mg2pg

def migrate_data(apps, schema_editor):
    result = mg2pg.migrate()
    return

class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_superuser'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
